/*
 * Project name:
     ThermalCameraDemo.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     14.5.2019.
 * Test configuration:
     MCU:             STM32F407ZG
     Dev.Board:       Fusion_for_STM32_Board_5_Capacitive
     Oscillator:      168000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 
Cloud :
  userName:  ti0pv6265gqrf5lf
  Password:  49a13f33-33dd-4d83-ae89-cca4453cd5f9

 */

#include "ThermalCameraDemo_objects.h"
#include "ThermalCameraDemo_resources.h"
#include "demo_types.h"
#include "demo_config.h"
#include "fonts.h"
#include "images.h"
#include "color_scale.h"
#include "demo_timer.h"

#define GET_PIX_NOR(col,row)            mlx90640To[((col) * 32) + (row)]
#define TA_SHIFT 9

/**************************************************************  G2C CLICK  ***/

//SENSOR remove if not used
static char g2c_sRef_tempMin[ 30 ] = "TC_TEMP_MIN";
static char g2c_sRef_tempMax[ 30 ] = "TC_TEMP_MAX";
static char g2c_sRef_tempAvg[ 30 ] = "TC_TEMP_AVG";
static char g2c_sRef_tempAmb[ 30 ] = "TC_TEMP_AMB";

// Commands
static char _ATE    [ 5 ] = "ATE1";
static char _AT     [ 3 ] = "AT";
static char _AT_CEN [ 9 ] = "AT+CEN=1";
static char _AT_NWCR[ 8 ] = "AT+NWCR";
static char _AT_NWC [ 9 ] = "AT+NWC=1";
static char _AT_BRCR[ 8 ] = "AT+BRCR";
static char _AT_BRC [ 9 ] = "AT+BRC=1";
static char _AT_DSET[ 8 ] = "AT+DSET";
static char _AT_PUB [ 7 ] = "AT+PUB";

/******************************************************************************/

float mlx90640To[768];
paramsMLX90640 mlx90640;
uint16_t eeMLX90640[832];
uint16_t mlx90640Frame[834];

int fScreen = 0;
uint8_t fMessage = 0;
float Ta = 0;
float tr = 0;
float emissivity = 0.95;

uint8_t Touch_new = 0;
uint8_t Touch_old = 0;

char demoText[ 100 ] = " ";

uint16_t color;
uint8_t rc = 0, cc = 0;
uint16_t matrix_cnt = 0;

float To_min_pixels = 50;
float To_max_pixels = 0;
double To_avg_pixels = 0;
char To_min_pxBuffer[20];
char To_max_pxBuffer[20];
char To_avg_pxBuffer[20];

char G2C_min_pxBuffer[20];
char G2C_max_pxBuffer[20];
char G2C_avg_pxBuffer[20];
char G2C_ambient_tempBuffer[20];

extern int8_t _min_value  ;
extern int8_t _low_value  ;
extern int8_t _med_value  ;
extern int8_t _high_value ;
extern int8_t _max_value  ;

/**************************************************************  G2C CLICK  ***/

void g2c_default_handler( uint8_t *rsp, uint8_t *evArgs )
{

}

void g2c_packCmd(uint8_t *cmd, uint8_t *mid, uint8_t *_end)
{
    char cmd_param[ 10 ] = "=\"";
    char mid_param[ 10 ] = "\",\"";
    char end_param[ 10 ] = "\"";

    uint8_t tmpBuf[ 80 ];
    memset(&tmpBuf[ 0 ], 0, 50);

    strcat ( &tmpBuf[ 0 ], cmd );
    strcat ( &tmpBuf[ 0 ], &cmd_param[0] );
    strcat ( &tmpBuf[ 0 ], mid );
    strcat ( &tmpBuf[ 0 ], &mid_param[0] );
    strcat ( &tmpBuf[ 0 ], _end );
    strcat ( &tmpBuf[ 0 ], &end_param[0] );

    g2c_cmdSingle( &tmpBuf[ 0 ] );
}

/******************************************************************************/

void systemInit()
{
    Delay_80us();

    /* Matrix RGB */
    mikrobus_gpioInit( _MIKROBUS3, _MIKROBUS_INT_PIN, _GPIO_INPUT );
    mikrobus_gpioInit( _MIKROBUS3, _MIKROBUS_CS_PIN, _GPIO_OUTPUT );
    mikrobus_gpioInit( _MIKROBUS3, _MIKROBUS_RST_PIN, _GPIO_OUTPUT );
    mikrobus_spiInit( _MIKROBUS3, &_MATRIXRGB_SPI_CFG[0] );
    
    /* IR Grid 2 click */
    mikrobus_i2cInit( _MIKROBUS2, &_IRGRID2_I2C_CFG[0] );
    
    /* ProxFusion 2 click*/
    mikrobus_gpioInit( _MIKROBUS5, _MIKROBUS_INT_PIN, _GPIO_INPUT );
    mikrobus_i2cInit( _MIKROBUS5, &_PROXFUSION2_I2C_CFG[0] );
    Delay_ms( 100 );
    
    // G2C
    mikrobus_gpioInit( _MIKROBUS4, _MIKROBUS_INT_PIN, _GPIO_INPUT );
    mikrobus_gpioInit( _MIKROBUS4, _MIKROBUS_RST_PIN, _GPIO_OUTPUT );
    mikrobus_gpioInit( _MIKROBUS4, _MIKROBUS_CS_PIN, _GPIO_OUTPUT );
    mikrobus_uartInit( _MIKROBUS4, &_G2C_UART_CFG[0] );
    
}

void applicationInit()
{
// TIMER INIT
    g2c_configTimer();

// DRIVER INIT
    g2c_uartDriverInit((T_G2C_P)&_MIKROBUS4_GPIO, (T_G2C_P)&_MIKROBUS4_UART);
    g2c_coreInit( g2c_default_handler, 1500 );
    g2c_modulePower( 0 );
    g2c_moduleReset();

// MODULE INIT
    g2c_cmdSingle( &_ATE[0] );
    g2c_cmdSingle( &_AT[0] );
    g2c_cmdSingle( &_AT_CEN[0] );
    Delay_ms(1000);
    g2c_cmdSingle  ( "AT+NWCR=\"MikroE Public\",\"mikroe.guest\"");
    Delay_ms(1000);
    g2c_cmdSingle( &_AT_NWC[0] );
    Delay_ms(1000);
    g2c_cmdSingle ( "AT+BRCR=\"9rms0hfizvktyw5d\",\"45c6e643-2cc2-4257-bbab-cf89db804af6\"" );
    Delay_ms(1000);
    g2c_cmdSingle( &_AT_BRC[0] );
    Delay_ms(1000);

    taskTime = 0;
    
    /*Matrix RGB click*/
    matrixrgb_spiDriverInit( (T_MATRIXRGB_P)&_MIKROBUS3_GPIO, (T_MATRIXRGB_P)&_MIKROBUS3_SPI );
    matrixrgb_deviceReset();

    matrixrgb_deviceInit( _MATRIXRGB_PATTERN_4S_MAP_6MM );
    matrixrgb_setPower( 1 );
    Delay_1sec();

    matrixrgb_setBrightness( 2 );
    matrixrgb_drawImage(TMP_IMAGE3_bmp);

    /* IR Grid 2 click */
    irgrid2_i2cDriverInit( (T_IRGRID2_P)&_MIKROBUS2_GPIO, (T_IRGRID2_P)&_MIKROBUS2_I2C, 0x33 );

    irgrid2_readEEPROM(eeMLX90640);
    irgrid2_ExtractParameters(eeMLX90640, &mlx90640);
    irgrid2_setRefreshRate( 0x03 ); // 4 Hz

    /* ProxFusion 2 click */
    proxfusion2_i2cDriverInit( (T_PROXFUSION2_P)&_MIKROBUS5_GPIO, (T_PROXFUSION2_P)&_MIKROBUS5_I2C, 0x44 );
    proxfusion2_init();
    proxfusion2_defaultConfig();
    Delay_100ms();
    
    Delay_ms( 1000 );
}

void g2cTask()
{
// SENSOR - Remove if not used
    if( taskTime > 1500 )
    {
        taskTime = 0;

        g2c_packCmd( &_AT_DSET[0], &g2c_sRef_tempMin[0], &G2C_min_pxBuffer[0]);
        g2c_packCmd( &_AT_DSET[0], &g2c_sRef_tempMax[0], &G2C_max_pxBuffer[0]);
        g2c_packCmd( &_AT_DSET[0], &g2c_sRef_tempAvg[0], &G2C_avg_pxBuffer[0]);
        g2c_packCmd( &_AT_DSET[0], &g2c_sRef_tempAmb[0], &G2C_ambient_tempBuffer[0]);
        g2c_cmdSingle( &_AT_PUB[0] );
    }
}

void create_martixImage()
{
    uint8_t pos;
    uint8_t rcnt;
    float temp_pixels;
    
    To_avg_pixels = 0;
    To_min_pixels = 50;
    To_max_pixels = 0;
    
    matrix_cnt = 16 * 64;
    for (rc = 0; rc < 24; rc++)
    {
        for (rcnt = 0; rcnt < 2; rcnt++)
        {
            for (cc = 0; cc < 32; cc++)
            {
                 temp_pixels = GET_PIX_NOR(rc, cc);
                 
                 color = color_scale_rgb_conversion( temp_pixels );
                 pos = matrix_cnt;
                 gImage_matrixImage[pos] = (uint8_t)(color & 0x00FF);
                 gImage_matrixImage[pos + 1 ] = (uint8_t)(color >> 8);
                 gImage_matrixImage[pos + 2 ] = (uint8_t)(color & 0x00FF);
                 gImage_matrixImage[pos + 3 ] = (uint8_t)(color >> 8);
                 matrix_cnt += 4;
                 
                 if(rcnt == 0)
                 {
                     if( temp_pixels < To_min_pixels && temp_pixels != 0) To_min_pixels = temp_pixels;
                     if( temp_pixels > To_max_pixels ) To_max_pixels = temp_pixels;
                     To_avg_pixels += temp_pixels;
                 }
            }
        }
    }
    To_avg_pixels /= 768.0;
    
    FloatToStr(To_min_pixels, G2C_min_pxBuffer);
    LTrim(G2C_min_pxBuffer);
    FloatToStr(To_max_pixels, G2C_max_pxBuffer);
    LTrim(G2C_max_pxBuffer);
    FloatToStr(To_avg_pixels, G2C_avg_pxBuffer);
    LTrim(G2C_avg_pxBuffer);
    FloatToStr(Ta - 5, G2C_ambient_tempBuffer);
    LTrim(G2C_avg_pxBuffer);
}

void _TempValue()
{
    IntToStr(_min_value, demoText);
    TFT_Set_Font(&Tahoma40x40, 0x0000, FO_HORIZONTAL);
    TFT_Write_Text(demoText, 180, 75);
    
    IntToStr(_low_value, demoText);
    TFT_Set_Font(&Tahoma40x40, 0x0000, FO_HORIZONTAL);
    TFT_Write_Text(demoText, 180, 155);
    
    IntToStr(_med_value, demoText);
    TFT_Set_Font(&Tahoma40x40, 0x0000, FO_HORIZONTAL);
    TFT_Write_Text(demoText, 180, 235);

    IntToStr(_high_value, demoText);
    TFT_Set_Font(&Tahoma40x40, 0x0000, FO_HORIZONTAL);
    TFT_Write_Text(demoText, 180, 310);
    
    IntToStr(_max_value, demoText);
    TFT_Set_Font(&Tahoma40x40, 0x0000, FO_HORIZONTAL);
    TFT_Write_Text(demoText, 180, 390);
}

void _TObject()
{
    TFT_Set_Font(&Tahoma40x40, 0xFFFF, FO_HORIZONTAL);
    TFT_Write_Text(To_min_pxBuffer, 565, 170);
    FloatToStr(To_min_pixels, To_min_pxBuffer);
    TFT_Set_Font(&Tahoma40x40, 0x0000, FO_HORIZONTAL);
    TFT_Write_Text(To_min_pxBuffer, 565, 170);

    TFT_Set_Font(&Tahoma40x40, 0xFFFF, FO_HORIZONTAL);
    TFT_Write_Text(To_max_pxBuffer, 565, 280);
    FloatToStr(To_max_pixels, To_max_pxBuffer);
    TFT_Set_Font(&Tahoma40x40, 0x0000, FO_HORIZONTAL);
    TFT_Write_Text(To_max_pxBuffer, 565, 280);
    
    TFT_Set_Font(&Tahoma40x40, 0xFFFF, FO_HORIZONTAL);
    TFT_Write_Text(To_avg_pxBuffer, 565, 385);
    FloatToStr(To_avg_pixels, To_avg_pxBuffer);
    TFT_Set_Font(&Tahoma40x40, 0x0000, FO_HORIZONTAL);
    TFT_Write_Text(To_avg_pxBuffer, 565, 385);
}

void applicationTask()
{
    g2cTask();
    if(fScreen == 0)
    {
        /* Calculate IR GRID matrix*/
        irgrid2_getFrameData(mlx90640Frame);
        Ta = irgrid2_GetTa(mlx90640Frame, &mlx90640);
        tr = Ta - TA_SHIFT;
        irgrid2_CalculateTo(mlx90640Frame, &mlx90640, emissivity, tr, mlx90640To);
        color_scale_init(Ta);

        /* Display Ambient temperature */
        TFT_Set_Font(&Tahoma40x40, 0x0679, FO_HORIZONTAL);
        TFT_Write_Text(demoText, 75, 389);
        TFT_Set_Font(&Tahoma40x40, 0x632C, FO_HORIZONTAL);
        FloatToStr(Ta - 5.0, demoText);
        TFT_Write_Text(demoText, 75, 389);

        /* Create matrix Image */
        create_martixImage();
        matrixrgb_drawImage(gImage_matrixImage);
        Delay_ms( 400 );

        /* Check touch */
        Touch_new = proxfusion2_readByte(0x13);
        Touch_new &= 0x02;
        
        if (Touch_new == 0x02 && Touch_old != 0x02)
        {
            fScreen = 1;
            DrawScreen(&Screen2);
            fMessage = 0;
            Delay_ms( 500 );
        }
        Touch_old = Touch_new;
    }
    else
    {
        Check_TP();
        
        /* First display */
        if(fMessage == 0)
        {
            _TempValue();
            _TObject();
            matrixrgb_drawImage(TMP_IMAGE1_bmp);
            fMessage = 1;
        }
        
         /* Check touch */
        Touch_new = proxfusion2_readByte(0x13);
        Touch_new &= 0x02;
        if (Touch_new == 0x02 && Touch_old != 0x02)
        {
            fScreen = 0;
            DrawScreen(&Screen1);
            Delay_ms( 500 );
        }
        Touch_old = Touch_new;
    }
}

void main()
{
    systemInit();
    applicationInit();
    Start_TP();

    while (1) 
    {
        applicationTask();
    }
}